# Generated by Django 6.0.6 on 2026-07-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('fname', models.CharField(max_length=20)),
                ('files', models.FileField(upload_to='files/')),
            ],
        ),
    ]
