# Generated by Django 6.0.6 on 2026-07-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datas',
            name='pimg',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
